server:
  port: ${SERVER_PORT}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_URL}
              predicates:
                - Path=/auth/**
                - Method=GET,POST,PUT,DELETE

            - id: user-service
              uri: ${USER_URL}
              predicates:
                - Path=/users/**
                - Method=GET,POST,PUT,DELETE

            - id: receipt-service
              uri: ${RECEIPT_URL}
              predicates:
                - Path=/receipt/**
                - Method=GET,POST,PUT,DELETE
